### ISSUE TITLE
Create Boulder Subsystem

### ISSUE THREAD

**Issue by BenBernardCIS** [frc5687/2016-Outlier2#11]
### New requirements, per discussion on 2/3/16
- A VictorSP for the intake motor
- A VictorSP for the shooter motor
- 2 digital inputs for the boulder position sensors
- An encoder for the shooter wheel
- A basic constructor method
- No commands/ other methods/ etc yet, we will add those later once we better define the behavior.

**Comment by BenBernardCIS** [comment]
We may want to split this into multiple issues...we can discuss that tomorrow.  In that case, this issue would only encompass the subsystem itself, not the commands.

**Comment by rtfoley** [comment]
A couple thoughts:
- Using photoelectric sensors for the various positions we need the boulder in, instead of using an encoder on the intake roller, would probably be more accurate. If the ball slips or gets knocked at all, the encoder will be out-of-sync from the ball position, whereas the sensors will give us a better picture of where the ball is.
- This might be a good place for a state machine, instead of individual flags.
- We will want to think about when we spin up the shooter to launch speed. Due to defense, we may not have time to get in position and then spin up.

**Comment by Julian-B** [comment]
About your last point: Right, so we could use the NavX to determine when we have crossed the Outer Works, and immediately begin spinning up the Shooter Wheel

**Comment by rtfoley** [comment]
true, but we would have to think about false-positives when we cross back-over into the neutral zone.

**Comment by rtfoley** [comment]
Re-opening this issue, lets create the boulder subsystem class with the following:
- A VictorSP for the intake motor
- A VictorSP for the shooter motor
- 2 digital inputs for the boulder position sensors
- An encoder for the shooter wheel
- A basic constructor method
- No commands/ other methods/ etc yet, we will add those later once we better define the behavior.

**Comment by rtfoley** [comment]
These were the original requirements, capturing them here so we can refer back to Ben's original thoughts.

_Older version needs:_
- VictorSP controller for shooter wheel(s)
- VictorSP controller for intake roller
- Encoder for measuring intake roller rotations
- Sensor to detect ball in "hopper"?

Commands:
- Intake 
  - Ensure the shooter wheel is stopped
  - Spin the intake roller forward full speed 
  - If we have the ball sensor, auto-stop intake and set a HasBoulder flag when ball is secure in  
- Bowl
  - Spin the intake roller reverse full speed
  - Wait preset time for ball to clear?
  - Continue to Reset?
- Prime 
  - Check that robot is level (ie, clear of defense ramps)?
  - Roll the intake roller 1/4 turn backwards (use a constant so we can tune)
  - Spin the shooter wheel to full 
  - Once the wheel is running full (either by encoder or time) set a Primed flag
- Shoot
  - Check for Primed?
  - Spin the intake rolller full forward
  - Wait a preset time for ball to clear
  - Continue to Reset?
- Cancel
  - Spin the shooter back down
  - Wait for the wheel to stop (either by encoder or time)
  - Roll the intake roller 1/4 turn forwards to re-stow boulder
  - Clear the Primed flag
- Reset
  - Spin the shooter back down
  - Wait for the wheel to stop (either by encoder or time)
  - Clear the Primed and HasBoulder flags
