### ISSUE TITLE
POT For Arm-Control

### ISSUE THREAD

**Issue by Julian-B** [frc5687/2016-Outlier2#113]
Configure POT for the Arms, so that we can add safeguards to prevent 'em from smashing the Electronics board.

This'll be useful:
wpilib.screenstepslive.com/s/4485/m/13809/l/241877-potentiometers-measuring-joint-angle-or-linear-motion

**Comment by rtfoley** [comment]
at minimum, we need basic limits in place that will stop the arm from moving too far in each direction. When the arm reaches/ goes past a certain potentiometer value, the arm should stop. The user should still be able to move the arm in the opposite direction.

**Comment by BenBernardCIS** [comment]
We need constants for potentiometer value at:
- [ ] Stowed position
- [ ] Straight up position
- [ ] Hall effect sensor (possibly a range)
- [ ] On the floor when robot is flat
- [ ] On the defense when robot is entering portcullis
- [ ] Holding the portcullis clear of the robot
- [ ] Just above the Cheval when approaching the Cheval
- [ ] Holding the cheval down

**Comment by TheMightyWarPig** [comment]
This can be done, the question is when

**Comment by wilstenholme** [comment]
Basic limits are ready, constants for each position shall be work in #137 after this gets merged.
