### ISSUE TITLE
Fix inverse command, sync camera, drive, and label.

### ISSUE THREAD

**Issue by Julian-B** [frc5687/2016-Outlier2#126]
All three of Camera, Drive, and DriveStation Label need to be oriented the same direction, and must stay the same when inversed.

**Comment by BenBernardCIS** [comment]
Also, positive speeds and directions should be towards the horns in autonomous mode, and the robot should always start up"facing" the horns.

**Comment by wilstenholme** [comment]
Closing as a part of merge of fix/week0.
