### ISSUE TITLE
Add shooter speed control to the dashboard

### ISSUE THREAD

**Issue by BenBernardCIS** [frc5687/2016-Outlier2#141]
We're finding that fresh boulders fly further than old worn out boulders.  The only way we have to compensate is by reducing shooter speed.  Drive team needs to be able to adjust shooter speed, but we don't want that to be a control that's easily bumped, so we think putting it on the dashboard makes the most sense.

This should be read by SetShooterSpeed on each use.

**Comment by JCharante** [comment]
Would a chooser with two options
- New Boulder
- Worn Out Boulder

make sense? You could have a conditional in everything that sets the shooter speed that gets the value of the chooser.

**Comment by BenBernardCIS** [comment]
This works for now.  Ryan, do you think we need finer control?  Like a slider that can run from .95 to 1.0?

**Comment by rtfoley** [comment]
@BenBernardCIS given that the field may contain a mix of new and used boulders, is this something we expect the drive team to change with each boulder? Was it a drastic difference in shot accuracy when using the same speed for new/used boulders?
