### ISSUE TITLE
Add Flashlight subsystem

### ISSUE THREAD

**Issue by BenBernardCIS** [frc5687/2016-Outlier2#150]
We need a Flashlight subsystem tied to the PCM to power the flashlight.
This should have methods to turn on and off the flashlight, which should be called by Prime and Fire, respectively.

**Comment by BenBernardCIS** [comment]
The flashlight is taking the place of a solenoid on the PCM, so you would follow this article: http://wpilib.screenstepslive.com/s/4485/m/13809/l/241866-operating-pneumatic-cylinders-solenoids

**Comment by rtfoley** [comment]
@BenBernardCIS the compressor uses a build-in closed loop control to operate, based on the status of a pressure sensor. I think we want to connect the light to a solenoid channel on the PCM, so we can turn it on and off as we need (similar to the vision camera ring lights)

**Comment by BenBernardCIS** [comment]
That's fine...then we can control both the ring-light and the flashlight spearately.
