### ISSUE TITLE
Roborio doesn't link to bridge on startup

### ISSUE THREAD

**Issue by BenBernardCIS** [frc5687/2016-Outlier2#21]
Currently, when the robot is powered on, the bridge takes a while to start up.  As a result, the roborio doesn't establish a link.  The workaround is to use the "reset" button on the roborio, but I can guarantee that will be forgotten in the heat of an event.  We need to figure out how to get the roborio to link to the bridge _without_ manual intervention.

**Comment by wilstenholme** [comment]
The OM5P-AN uses 12V 2A, 18-24V POE for ethernet is faster. Rewiring solves bridge problem. Solved.

**Comment by rtfoley** [comment]
@wilstenholme does your solution following the required wiring path per the rules?

**Comment by wilstenholme** [comment]
@rtfoley yeah, it does comply to the rule. Per FRC 2016, https://wpilib.screenstepslive.com/s/4485/m/24166/l/144971-wiring-the-2016-frc-control-system

**Comment by rtfoley** [comment]
Ok thanks, I see it now (rule R43).
