### ISSUE TITLE
Show drive motor current draw on dashboard

### ISSUE THREAD

**Issue by rtfoley** [frc5687/2016-Outlier2#22]
Use the CAN connection to the Power Distribution Panel to get the current draw for each of the drive motors, then show these values on the Smart Dashboard.

More information: [https://wpilib.screenstepslive.com/s/4485/m/13809/l/219414-power-distribution-panel](https://wpilib.screenstepslive.com/s/4485/m/13809/l/219414-power-distribution-panel)

**Comment by rtfoley** [comment]
Lets wait to start work on this (in other words, don't create a branch for this yet) until we close out some of the other drive-related work.

**Comment by rtfoley** [comment]
You can use the SmartDashboard code in Robot's sendIMUData() method as a guide for putting data on the dashboard. We should have a number for each of the 4 drive motors.

**Comment by BenBernardCIS** [comment]
Looks good so far, but it would be a good idea to move the getCurrent parameters to Constants (or perhaps RobotMap).  Ryan, any preference?

**Comment by rtfoley** [comment]
Yeah let's put the constants for which PDP channels we are using for the drive motors in the RobotMap class, since that deals with where things connect on the bot. I agree looks good so far.

**Comment by BenBernardCIS** [comment]
We tested this on the board this morning.
