### ISSUE TITLE
Get GRIP running on the roborio

### ISSUE THREAD

**Issue by BenBernardCIS** [frc5687/2016-Outlier2#36]
We thought we had 4 choices for our vision processing:
1) GRIP on the DS sending tracking variables back to the rio
2) GRIP on the rio 
3) OpenCV on the rio
4) OpenCV on a raspberry pi sending tracking variables to the rio

We now know that (1) cannot work b/c GRIP on the DS can't receive video from a USB cam on the rio.
So, we need to see if we can get the GRIP running on the rio itself.

**Comment by rtfoley** [comment]
Not going to do this for 2016
