### ISSUE TITLE
Show ball detection sensor status on the dashboard

### ISSUE THREAD

**Issue by rtfoley** [frc5687/2016-Outlier2#41]
- [x] Add digital inputs to the Intake for the ball detection sensors (use RobotMap to specify what ports the sensors connect to)
- [x] Add a method to the Intake subsystem to send data to the Smart Dashboard. This method should send the values for both ball sensors, with correct labels
- [x] Add a call to the above method in Robot.teleopPeriodic()

**Comment by rtfoley** [comment]
This should be done after #53

**Comment by wilstenholme** [comment]
closed by #80
