### ISSUE TITLE
Show shooter wheel speed on the dashboard

### ISSUE THREAD

**Issue by rtfoley** [frc5687/2016-Outlier2#42]
- [ ] Add an encoder to the shooter subsystem (use RobotMap to specify what ports the encoder channels connect to)
- [ ] Add a method to the Shooter subsystem to send data to the Smart Dashboard. This method should send the current RPM of the shooter to the dashboard
- [ ] Add a call to the above method in Robot.teleopPeriodic()

**Comment by BenBernardCIS** [comment]
In case we don't end up with an encoder, we can STILL show an "at speed" indicator on the dashboard  once the shooter wheel has been spinning long enough to be at speed.  The "spin-up time" should be controlled via a  constant.

**Comment by BenBernardCIS** [comment]
Since we don't have an encoder, can you:
1) Add an "atSpeed" boolean to the Shooter subsystem
2) Expose it via a public getter and setter
3) Have the setter send the setting to the dashboard
4) Have the Shooter commands set/clear the flag

**Comment by BenBernardCIS** [comment]
This is more important than we previously thought because the drive team can't tell the shooter wheel state from way across the field, and loses track in the heat of the match
