### ISSUE TITLE
Clean up RobotMap class

### ISSUE THREAD

**Issue by rtfoley** [frc5687/2016-Outlier2#63]
The RobotMap class members are somewhat unorganized, we should clean them up by structuring the class like the Constants class.

For example:

``` java
public class RobotMap {
    public static class Drive {
        public static final int LEFT_MOTORS = 1;
    }

    public static class Shooter {
        public static final int WHEEL_MOTOR = 2;
    }
}
```

Acceptance:
- Each subsystem should have it's own subclass
- constants should be in all caps
- Other classes refactored appropriately to use new constant names

**Comment by wilstenholme** [comment]
Let's work on this issue when the other PRs are merged first
